services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  whatsapp:
    extends:
      file: docker-compose.base.yml
      service: whatsapp
    environment:
      - WHATSAPP_WEBHOOK=http://host.docker.internal:8000/webhook

volumes:
  wa_llm_whatsapp:
    name: wa_llm_whatsapp
  wa_llm_postgres:
    name: wa_llm_postgres