services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  web-server:
    extends:
      file: docker-compose.base.yml
      service: web-server
    environment:
      - DB_URI=postgresql+asyncpg://user:password@postgres:5432/postgres
      - WHATSAPP_HOST=http://localhost:3003
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  wa_llm_postgres:
    name: wa_llm_postgres
