import sqlmodel

"""add_is_relevant_to_message_table

Revision ID: f470ad6f6e93
Revises: bbba88e22126
Create Date: 2025-10-19 15:41:01.200408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f470ad6f6e93'
down_revision: Union[str, None] = 'bbba88e22126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_relevant', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_relevant')
    # ### end Alembic commands ###
