import sqlmodel

"""add_reasoning_to_message_table

Revision ID: 6e364fa447c2
Revises: f470ad6f6e93
Create Date: 2025-10-19 15:41:42.704041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e364fa447c2'
down_revision: Union[str, None] = 'f470ad6f6e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'reasoning')
    # ### end Alembic commands ###
