import sqlmodel

"""add_input_and_output_token_counts_to_message_table

Revision ID: e9e3166f06a6
Revises: 99204d509d36
Create Date: 2025-10-19 16:50:18.013574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e3166f06a6'
down_revision: Union[str, None] = '99204d509d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('relevancy_input_tokens', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('relevancy_output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'relevancy_output_tokens')
    op.drop_column('message', 'relevancy_input_tokens')
    # ### end Alembic commands ###
