import sqlmodel

"""add_relevancy_total_token_count_to_message_table

Revision ID: 99204d509d36
Revises: 6e364fa447c2
Create Date: 2025-10-19 16:10:45.148858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99204d509d36'
down_revision: Union[str, None] = '6e364fa447c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('relevancy_total_token_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'relevancy_total_token_count')
    # ### end Alembic commands ###
