name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '**.py'
  workflow_call:

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Test with pytest
        run: |
          uv run coverage run --source=pytest_evals -m pytest --junitxml=junit/test-results.xml
          uv run coverage xml coverage.xml
      - name: Get Cover
        uses: orgoro/coverage@v3
        if: github.event_name == 'pull_request'
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: always()
        with:
          files: |
            junit/**/*.xml
            junit/**/*.trx
            junit/**/*.json